config/routes.rb
Rails.application.routes.draw do
    
    
  resources :docusigns
  resources :webids
  resources :web_ids
  resources :prefills
    devise_for :users, only: :omniauth_callbacks,
               controllers: {omniauth_callbacks: 'omniauth_callbacks'}
    
    scope "(:locale)", locale: /en|es|de|pt/ do
    
        get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth
        
        devise_for :users,
                   path_names:  {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
                   skip: :omniauth_callbacks,
                   controllers: {omniauth_callbacks: 'omniauth_callbacks', passwords: 'passwords', registrations: 'registrations'}
        
        get '/:locale' => 'users#draft_applications'
        root to: 'users#draft_applications'
        
        get 'pages/landing' => 'pages#landing'
        get 'pages/impressum' => 'pages#impressum'
        get 'pages/terms_and_conditions' => 'pages#terms_and_conditions'
        get 'pages/registration_terms_and_conditions' => 'pages#registration_terms_and_conditions'
        get 'pages/guidelines' => 'pages#guidelines'
        get 'pages/advice' => 'pages#advice'
        get 'pages/contacted_exporter' => 'pages#contacted_exporter'
        get 'pages/broker_option' => 'pages#broker_option'
        get 'pages/welcome' => 'pages#welcome'
        get 'pages/broker_default' => 'pages#broker_default'
        get 'pages/products' => 'pages#products'
        get 'pages/advice_insurance' => 'pages#advice_insurance'
        get 'pages/advice_credit' => 'pages#advice_credit'
        get 'pages/advice_refinance' => 'pages#advice_refinance'
        get 'pages/invite_or_fill_yourself_export_appilcation' => 'pages#invite_or_fill_yourself_export_appilcation'
        get 'pages/invite_or_fill_yourself_insurance' => 'pages#invite_or_fill_yourself_insurance'
        get 'pages/application_submitted' => 'pages#application_submitted'
        get 'pages/importer_information_saved' => 'pages#importer_information_saved'
        get 'pages/document_prefill_saved' => 'pages#document_prefill_saved'
        get 'pages/webid_instructions' => 'pages#webid_instructions'
        get 'pages/candis' => 'pages#candis'

        resources :insurances
        resources :export_applications
        resources :credits
        resources :invite_exporters
        resources :refinances
        resources :onboardings
        resources :importer_informations

        resources :users, only: [:show] do
            member do
                get 'submitted_applications'
                get 'approved_applications'
                get 'draft_applications'
                get 'all_applications'
                get 'invite_exporters'
                get 'broker_filled_applications'
            end
        end
    end
	
end

app/models/insurance.rb
class Insurance < ApplicationRecord
    belongs_to :user
    has_many :insurance_supplies_from_foreign_origins, dependent: :destroy
    has_many :insurance_guarantees, dependent: :destroy
    has_many :insurance_agreed_payments, dependent: :destroy
    has_many :insurance_agreed_payment_mid_longs, dependent: :destroy
    has_many :insurance_multiple_shipments, dependent: :destroy
    has_many :insurance_source_of_funds, dependent: :destroy
    has_many :insurance_application_of_funds, dependent: :destroy
    has_many :insurance_extra_billed_items, dependent: :destroy
    has_many :insurance_special_repayment_profiles, dependent: :destroy

    accepts_nested_attributes_for :insurance_supplies_from_foreign_origins,
                                  allow_destroy: true

    accepts_nested_attributes_for :insurance_guarantees,
                                  allow_destroy: true

    accepts_nested_attributes_for :insurance_agreed_payments,
                                  allow_destroy: true

    accepts_nested_attributes_for :insurance_agreed_payment_mid_longs,
                                  allow_destroy: true

    accepts_nested_attributes_for :insurance_multiple_shipments,
                                  allow_destroy: true

    accepts_nested_attributes_for :insurance_source_of_funds,
                                  allow_destroy: true

    accepts_nested_attributes_for :insurance_application_of_funds,
                                  allow_destroy: true

    accepts_nested_attributes_for :insurance_extra_billed_items,
                                  allow_destroy: true

    accepts_nested_attributes_for :insurance_special_repayment_profiles,
                                  allow_destroy: true
    
    has_attached_file :annual_financial_statement_importer, :storage => :cloudinary, :cloudinary_resource_type => :image, :path => "insurances/:attachment/:id/:style/:filename",
                      styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :annual_financial_statement_importer, content_type: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf']

    has_attached_file :annual_financial_statement_importer_second_last, :storage => :cloudinary, :cloudinary_resource_type => :image,  :path => "insurances/:attachment/:id/:style/:filename",
                      styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :annual_financial_statement_importer_second_last, content_type: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf']
    
    has_attached_file :credit_bureaus_importer, :storage => :cloudinary, :cloudinary_resource_type => :image,  :path => "insurances/:attachment/:id/:style/:filename",
                      styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :credit_bureaus_importer, content_type: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf']

    has_attached_file :self_declaration, :storage => :cloudinary, :cloudinary_resource_type => :image,  :path => "insurances/:attachment/:id/:style/:filename",
                      styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :self_declaration, content_type: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf']

    has_attached_file :export_contract_or_bills, :storage => :cloudinary, :cloudinary_resource_type => :image,  :path => "insurances/:attachment/:id/:style/:filename",
                      styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :export_contract_or_bills, content_type: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf']
    
    has_attached_file :project_memorandum_exporter_business, :storage => :cloudinary, :cloudinary_resource_type => :image,  :path => "insurances/:attachment/:id/:style/:filename",
                      styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :project_memorandum_exporter_business, content_type: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf']

    has_attached_file :environment_social_audit, :storage => :cloudinary, :cloudinary_resource_type => :image,  :path => "insurances/:attachment/:id/:style/:filename",
                      styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :environment_social_audit, content_type: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf']

    has_attached_file :other_document, :storage => :cloudinary, :cloudinary_resource_type => :image,  :path => "insurances/:attachment/:id/:style/:filename",
                      styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :other_document, content_type: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf']
    
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/views/insurances/_application_summary_card_version_1.html.erb
<div class="col-md-6">
  <div class="panel panel-default">
    <div class="panel-body">

      <div class="row">
        <div class="col-sm-6">
          <h4 class="text-babu">Importer</h4>
        </div>
        <div class="col-sm-6">
          <%= insurance.importer_company_name %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-6">
          <h4 class="text-babu">Destination</h4>
        </div>
        <div class="col-sm-6">
          <%= insurance.importer_country %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-6">
          <h4 class="text-babu">Product</h4>
        </div>
        <div class="col-sm-6">
          <%= insurance.exported_goods_type %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-6">
          <h4 class="text-babu">Price</h4>
        </div>
        <% if insurance.price %>
          <div class="col-sm-6">
            &#x20AC; <%= insurance.price %>
          </div>
        <% else %>
          <div class="col-sm-6 text-red">
            MISSING
          </div>
        <% end %>
      </div>

      <div class="row">
        <div class="col-sm-6">
          <h4 class="text-babu">Last Updated at</h4>
        </div>
        <div class="col-sm-6">
          <%= insurance.updated_at.strftime('%d %b %Y') %>
        </div>
      </div>

      <hr>

      <div class="row">
        <div class="col-sm-12">
          <% if can_edit %>
            <%= link_to "Update", edit_insurance_path(insurance.user_id), class: "btn btn-form pull-right"%>
          <% else %>
            <div class="btn btn-form pull-right">
              View
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/insurances/_listing.html.erb
<div class="row">
  <% applications.each do |insurance| %>
    <%= render partial: "insurances/application_listing_card",
               locals:  {insurance: insurance,
                        can_edit: can_edit} %>
  <% end %>
</div>

app/views/insurances/_overview.html.erb
<%= render "overview_top.html.erb"%>
<%= render "overview_header.html.erb"%>
<%= render "overview_content.html.erb"%>

app/views/insurances/_overview_content.html.erb
<div class="overview_content">
    <div class="row">
        <div class="col s12">
            <ul class="tabs">
                <li class="tab col s3"><a class="active" href="#company"><%= t('company') %></a></li>
                <li class="tab col s3"><a href="#your_importer"><%= t('your_importer') %></a></li>
                <li class="tab col s3"><a href="#business_heading"><%= t('business_heading') %></a></li>
                <li class="tab col s3"><a href="#finance_and_payment"><%= t('finance_and_payment') %></a></li>
            </ul>
        </div>
        <div id="company" class="col s12">
            <div class="handex-form-container">
                <div class="container">
                    <div class="section">
                        
                        <ul class="collection with-header">
                            <% @insurance.attributes.each do |attr_name, attr_value|
                                next if (attr_name == "id" or !@insurance_company_attr_list.include? attr_name)    %>
                                <li class="collection-item">
                                    <div class="overview-item">
                                        <%= t(attr_name) %>
                                    </div>
                                    
                                    <div class="secondary-content">
                                        <%= if !attr_value.nil? and attr_value == t('please_select')
                                                t('not_selected_yet')
                                            elsif !attr_value.nil? and attr_value == "insurance"
                                                t('insurance')
                                            elsif !attr_value.nil? and !attr_value
                                                t('no')
                                            elsif !attr_value.nil? and attr_value == true
                                                t('yes')
                                            elsif !attr_name.nil? and attr_name != '' and (attr_value.nil? or attr_value == '')
                                                t('no_value')
                                            elsif !attr_value.nil?
                                                attr_value
                                            end
                                        %>
                                    </div>
                                </li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div id="your_importer" class="col s12">
            <div class="handex-form-container">
                <div class="container">
                    <div class="section">
                        
                        <ul class="collection with-header">
                            <% @insurance.attributes.each do |attr_name, attr_value|
                                next if (attr_name == "id" or !@insurance_your_importer_attr_list.include? attr_name)     %>
                                <li class="collection-item">
                                    <div class="overview-item">
                                        <%= t(attr_name) %>
                                    </div>
                                    
                                    <div class="secondary-content">
                                        <%= if !attr_value.nil? and attr_value == t('please_select')
                                                t('not_selected_yet')
                                            elsif !attr_value.nil? and attr_value == "insurance"
                                                t('insurance')
                                            elsif !attr_value.nil? and !attr_value
                                                t('no')
                                            elsif !attr_value.nil? and attr_value == true
                                                t('yes')
                                            elsif !attr_name.nil? and attr_name != '' and (attr_value.nil? or attr_value == '')
                                                t('no_value')
                                            elsif !attr_value.nil?
                                                attr_value
                                            end
                                        %>
                                    </div>
                                </li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div id="business_heading" class="col s12">
            <div class="handex-form-container">
                <div class="container">
                    <div class="section">
                        
                        <ul class="collection with-header">
                            <% @insurance.attributes.each do |attr_name, attr_value|
                                next if (attr_name == "id" or !@insurance_business_attr_list.include? attr_name)      %>
                                <li class="collection-item">
                                    <div class="overview-item">
                                        <%= t(attr_name) %>
                                    </div>
                                    <div class="secondary-content">
                                        <%= if !attr_value.nil? and attr_value == t('please_select')
                                                t('not_selected_yet')
                                            elsif !attr_value.nil? and attr_value == "insurance"
                                                t('insurance')
                                            elsif !attr_value.nil? and !attr_value
                                                t('no')
                                            elsif !attr_value.nil? and attr_value == true
                                                t('yes')
                                            elsif !attr_name.nil? and attr_name != '' and (attr_value.nil? or attr_value == '')
                                                t('no_value')
                                            elsif !attr_value.nil?
                                                attr_value
                                            end
                                        %>
                                    </div>
                                </li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div id="finance_and_payment" class="col s12">
            <div class="handex-form-container">
                <div class="container">
                    <div class="section">
                        
                        <ul class="collection with-header">
                            <% @insurance.attributes.each do |attr_name, attr_value|
                                next if (attr_name == "id" or !@insurance_finance_and_payment_attr_list.include? attr_name)      %>
                                <li class="collection-item">
                                    <div class="overview-item">
                                        <%= t(attr_name) %>
                                    </div>
                                    <div class="secondary-content">
                                        <%= if !attr_value.nil? and attr_value == t('please_select')
                                                t('not_selected_yet')
                                            elsif !attr_value.nil? and attr_value == "insurance"
                                                t('insurance')
                                            elsif !attr_value.nil? and !attr_value
                                                t('no')
                                            elsif !attr_value.nil? and attr_value == true
                                                t('yes')
                                            elsif !attr_name.nil? and attr_name != '' and (attr_value.nil? or attr_value == '')
                                                t('no_value')
                                            elsif !attr_value.nil?
                                                attr_value
                                            end
                                        %>
                                    </div>
                                </li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.tabs').tabs();
    });
</script>

app/views/insurances/_overview_header.html.erb
<div class="overview-header">
    <div class="container center">
        <div class="col s12 m12">
            <ul>
                <li><%= t('importer') %>
                    <div class="overview_header_value">
                        <%= (@insurance.importer_company_name.nil? or (!@insurance.importer_company_name.nil? and @insurance.importer_company_name.to_s.empty?) or (!@insurance.importer_company_name.nil? and @insurance.importer_company_name.to_s == t('please_select'))) ? render('shared/missing_icon') : @insurance.importer_company_name %>
                    </div>
                </li>
                <li><%= t('product') %>
                    <div class="overview_header_value">
                        <%= (@insurance.exported_goods_type_two.nil? or (!@insurance.exported_goods_type_two.nil? and @insurance.exported_goods_type_two.to_s.empty?) or (!@insurance.exported_goods_type_two.nil? and @insurance.exported_goods_type_two.to_s == t('please_select')) or (!@insurance.exported_goods_type_two.nil? and @insurance.exported_goods_type_two.to_s == t('please_select_corresponding_option'))) ? render('shared/missing_icon') : @insurance.exported_goods_type_two %>
                    </div>
                </li>
                <li><%= t('contract_value') %>
                    <div class="overview_header_value">
                        <%= (@insurance.contract_value.nil? or (!@insurance.contract_value.nil? and @insurance.contract_value.to_s.empty?) or (!@insurance.contract_value.nil? and @insurance.contract_value.to_s == t('please_select'))) ? render('shared/missing_icon') : @insurance.contract_value %>
                    </div>
                </li>
                <li><%= t('application_sent_at') %>
                    <div class="overview_header_value">
                        <%= (@insurance.created_at.nil? or (!@insurance.created_at.nil? and @insurance.created_at.to_s.empty?) or (!@insurance.created_at.nil? and @insurance.created_at.to_s == t('please_select'))) ? render('shared/missing_icon') : @insurance.created_at %>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>

app/views/insurances/_overview_top.html.erb
<div class="overview-top submitted">
  <div class="row">
    <div class="col s5 overview-top-icon">
      <%= link_to :back do %>
        <i class="material-icons">arrow_back</i>
      <% end %>
    </div>
    <div class="col s6 overview-top-icon">
      <div class="valign-wrapper">
        <i class="material-icons">timer</i>
        <div>
          <strong><%= t('application_sent') %></strong>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/insurances/_overview_top_editable.html.erb
<div class="overview-top draft">
  <div class="row">
    <div class="col s4 overview-top-icon">
      <%= link_to :back do %>
        <i class="material-icons">arrow_back</i>
      <% end %>
    </div>
    <div class="col s4 overview-top-icon">
      <div class="valign-wrapper">
        <div class="valign h_centered">
          <i class="custom_icon reciept-icon-white"></i>
          <strong><%= t('draft_application') %></strong>
        </div>
      </div>
    </div>
    <div class="col s4 overview-top-button">
      <%= form_for(@insurance, local: true, html: {multipart: true}, id: "export-application-portal") do |form| %>
        <%= link_to t('edit'), edit_insurance_path(@insurance), class: "btn handex-btn z-depth-0 right" %>
      <% end %>
    </div>
  </div>
</div>

app/views/insurances/_show_editable.html.erb
<%= render 'shared/navbar' %>
<p id="notice" class="" hidden><%= notice %></p>
<%= render "overview_top_editable.html.erb"%>
<%= render "overview_header.html.erb"%>
<%= render "overview_content.html.erb"%>

app/views/insurances/_show_non_editable.html.erb
<%= render 'shared/navbar' %>
<p id="notice" class="" hidden><%= notice %></p>
<%= render "overview_top.html.erb"%>
<%= render "overview_header.html.erb"%>
<%= render "overview_content.html.erb"%>

app/views/insurances/edit.html.erb
<%= render 'shared/navbar' %>
<%= render 'form', insurance: @insurance %>

app/views/insurances/index.html.erb
<%= render 'shared/navbar' %>

app/views/insurances/new.html.erb
<%= render 'shared/navbar' %>
<%= render 'form', insurance: @insurance %>

app/views/insurances/show.html.erb
<% if @insurance.application_status == "SUBMITTED" || @insurance.application_status == "APPROVED" %>
    <%= render "show_non_editable.html.erb" %>
<% elsif @insurance.application_status == "DRAFT" %>
  <%= render "show_editable.html.erb" %>
<% end %>

app/views/insurances/summary_for_user.html.erb
<p id="notice"><%= notice %></p>
<h1 class="text-center">Summary</h1>
<br>

<% panel_names = ["important_first" , "financing",  'customer', 'important_at_end'] %>
<% panel_headings = ["Das wichtigste zuerst" , "Ihre Finanzierung", 'Ihr Kunde', 'Notwendiges zum Schluss'] %>

<div class='row'>
  <% panel_names.zip(panel_headings).each do |panel_name, panel_title| %>
    <div class='col-md-8 col-md-offset-2 text-justify'>
      <div class="panel panel-default">

        <div class="panel-heading">
          <%= panel_title %>
        </div>

        <div class="panel-body">
          <%= form_with(model: @insurance, local: true, id: "customer-portal") do |form| %>
            <%= render partial: "insurances/summary/user/#{panel_name}.html.erb", locals: {insurance: @insurance, form: form} %>
          <% end %>
        </div>

      </div>
    </div>
  <% end %>
</div>