config/routes.rb
Rails.application.routes.draw do
    
    
  resources :docusigns
  resources :webids
  resources :web_ids
  resources :prefills
    devise_for :users, only: :omniauth_callbacks,
               controllers: {omniauth_callbacks: 'omniauth_callbacks'}
    
    scope "(:locale)", locale: /en|es|de|pt/ do
    
        get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth
        
        devise_for :users,
                   path_names:  {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
                   skip: :omniauth_callbacks,
                   controllers: {omniauth_callbacks: 'omniauth_callbacks', passwords: 'passwords', registrations: 'registrations'}
        
        get '/:locale' => 'users#draft_applications'
        root to: 'users#draft_applications'
        
        get 'pages/landing' => 'pages#landing'
        get 'pages/impressum' => 'pages#impressum'
        get 'pages/terms_and_conditions' => 'pages#terms_and_conditions'
        get 'pages/registration_terms_and_conditions' => 'pages#registration_terms_and_conditions'
        get 'pages/guidelines' => 'pages#guidelines'
        get 'pages/advice' => 'pages#advice'
        get 'pages/contacted_exporter' => 'pages#contacted_exporter'
        get 'pages/broker_option' => 'pages#broker_option'
        get 'pages/welcome' => 'pages#welcome'
        get 'pages/broker_default' => 'pages#broker_default'
        get 'pages/products' => 'pages#products'
        get 'pages/advice_insurance' => 'pages#advice_insurance'
        get 'pages/advice_credit' => 'pages#advice_credit'
        get 'pages/advice_refinance' => 'pages#advice_refinance'
        get 'pages/invite_or_fill_yourself_export_appilcation' => 'pages#invite_or_fill_yourself_export_appilcation'
        get 'pages/invite_or_fill_yourself_insurance' => 'pages#invite_or_fill_yourself_insurance'
        get 'pages/application_submitted' => 'pages#application_submitted'
        get 'pages/importer_information_saved' => 'pages#importer_information_saved'
        get 'pages/document_prefill_saved' => 'pages#document_prefill_saved'
        get 'pages/webid_instructions' => 'pages#webid_instructions'
        get 'pages/candis' => 'pages#candis'

        resources :insurances
        resources :export_applications
        resources :credits
        resources :invite_exporters
        resources :refinances
        resources :onboardings
        resources :importer_informations

        resources :users, only: [:show] do
            member do
                get 'submitted_applications'
                get 'approved_applications'
                get 'draft_applications'
                get 'all_applications'
                get 'invite_exporters'
                get 'broker_filled_applications'
            end
        end
    end
	
end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
      <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>');
      <% end %>
  </script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
<script type="text/javascript">
    <% flash.each do |key, value| %>
    <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
    toastr['<%= type %>']('<%= value %>');
    <% end %>
</script>
<% end %>

app/views/shared/_missing_icon.html.erb
<i class="material-icons red-text">report</i>

app/views/shared/_navbar.erb
<nav class="white z-depth-0">
    
    <div class="nav-wrapper z-depth-1">
        
        <a href="/" class="brand-logo"> <%= image_tag "HandEX_logo4.png", class: "handex-nav-logo" %></a>
        
        <ul class="right hide-on-med-and-down handex-nav-icon">
            <li>
                <a class="top-navigation-icons waves-effect" href=<%= edit_user_registration_path %>><i class="material-icons">account_circle</i></a>
            </li>
            
            <% if current_user.user_type == 3 %>
                <li>
                    <a class="top-navigation-icons waves-effect" href=<%= broker_filled_applications_user_path(current_user.id) %>><i class="material-icons">add_alert</i></a>
                </li>
            <% else %>
                <li>
                    <a class="top-navigation-icons waves-effect" href=<%= submitted_applications_user_path(current_user.id) %>><i class="material-icons">add_alert</i></a>
                </li>
            <% end %>
            <li>
                <a class="top-navigation-icons waves-effect dropdown-trigger" data-target="dropdown1"><i class="material-icons">settings</i></a>
            </li>
        </ul>
    
    </div>
</nav>

<ul id="dropdown1" class="dropdown-content">
    
    <% if current_user.user_type == 3 %>
        <li><%= link_to t('submitted_application'), broker_filled_applications_user_path(current_user.id) %></li>
    <% else %>
        <li><%= link_to t('submitted_application'), submitted_applications_user_path(current_user.id) %></li>
    <% end %>
    
    <li><%= link_to t('your_profile'), edit_user_registration_path %></li>
    <!--    <li class="divider"></li>-->
    <li> <%= button_to t('logout'), destroy_user_session_path, method: :get, class: "handex-btn-logout" %> </li>

</ul>

<script>
    $(".dropdown-trigger").dropdown();
</script>

app/views/shared/_navbar.html.erb
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">

    <div class="col-xs-10 col-sm-10 hidden-md hidden-lg no-padding">
        <div class="flex-container">
            <div class="navbar-header">
                <a href="/" class="smooth"><%= image_tag "HandEX_logo4.png", style: 'height:3em;width:auto; margin-left: 1em; margin-top: 1em; margin-bottom: 1em' %></a>
            </div>
            <ul class="nav navbar-nav navbar-right navbar-text">

                <% if (!user_signed_in?) %>
                    <li><%= link_to "Anmelden", new_user_session_path %></li>
                    <li><%= link_to "Registrieren", new_user_registration_path %></li>

                <% else %>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                           role="button" aria-haspopup="true" aria-expanded="false">
                            <%= image_tag "user1.png", class: "img-circle avatar-small" %>&nbsp;
                            <%= current_user.fullname %>  <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu">
                            <!--                        <li><%#= link_to "Edit Profile", edit_user_registration_path %></li>-->
                            <li><%= link_to "Ausloggen", destroy_user_session_path, method: :delete %></li>
                        </ul>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>

    <div class="col-lg-10 col-md-10 hidden-xs hidden-sm col-lg-offset-1 col-md-offset-1 no-padding">
        <div class="container">
            <div class="navbar-header">
                <a href="/"> <%= image_tag "HandEX_logo4.png", style: 'height:4em;width:auto; margin-top: 1em; margin-bottom: 1em' %></a>
            </div>

            <ul class="nav navbar-nav navbar-right navbar-text">

                <% if (!user_signed_in?) %>
                    <li><%= link_to "Anmelden", new_user_session_path %></li>
                    <li><%= link_to "Registrieren", new_user_registration_path %></li>

                <% else %>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                           role="button" aria-haspopup="true" aria-expanded="false">
                            <%= image_tag "user1.png", class: "img-circle avatar-small" %>&nbsp;
                            <%= current_user.fullname %>  <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu">
                            <!--                        <li><%#= link_to "Edit Profile", edit_user_registration_path %></li>-->
                            <li><%= link_to "Ausloggen", destroy_user_session_path, method: :delete %></li>
                        </ul>
                    </li>
                <% end %>
            </ul>
        </div>

    </div>

</nav>

app/views/shared/_navbar_blue.erb
<nav class="white z-depth-0">

  <div class="nav-wrapper z-depth-1">

    <a href="/" class="brand-logo"> <%= image_tag "HandEX_blue_logo.png", class: "handex-nav-logo", style: 'height:1.5em; width:auto; margin-left: 1em; margin-top: 0.4em; margin-bottom: 0.5em' %></a>

    <ul class="right hide-on-med-and-down handex-nav-icon">

      <li><a class="top-navigation-icons waves-effect" href=<%= edit_user_registration_path %> ><i class="material-icons">account_circle</i></a></li>

      <li><a class="top-navigation-icons waves-effect" href=<%= submitted_applications_user_path(current_user.id) %> ><i class="material-icons">add_alert</i></a></li>

      <li><a class="top-navigation-icons waves-effect dropdown-trigger" data-target="dropdown1"><i class="material-icons">settings</i></a></li>
    </ul>

  </div>
</nav>

<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to t('submitted_application'), submitted_applications_user_path(current_user.id) %></li>
  <li><%= link_to t('your_profile'), edit_user_registration_path %></li>
  <!--    <li class="divider"></li>-->
  <li> <%= button_to t('logout'), destroy_user_session_path, method: :get, class: "handex-btn-logout" %> </li>

</ul>

<script>
    $(".dropdown-trigger").dropdown();
</script>