config/routes.rb
Rails.application.routes.draw do
    
    
  resources :docusigns
  resources :webids
  resources :web_ids
  resources :prefills
    devise_for :users, only: :omniauth_callbacks,
               controllers: {omniauth_callbacks: 'omniauth_callbacks'}
    
    scope "(:locale)", locale: /en|es|de|pt/ do
    
        get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth
        
        devise_for :users,
                   path_names:  {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
                   skip: :omniauth_callbacks,
                   controllers: {omniauth_callbacks: 'omniauth_callbacks', passwords: 'passwords', registrations: 'registrations'}
        
        get '/:locale' => 'users#draft_applications'
        root to: 'users#draft_applications'
        
        get 'pages/landing' => 'pages#landing'
        get 'pages/impressum' => 'pages#impressum'
        get 'pages/terms_and_conditions' => 'pages#terms_and_conditions'
        get 'pages/registration_terms_and_conditions' => 'pages#registration_terms_and_conditions'
        get 'pages/guidelines' => 'pages#guidelines'
        get 'pages/advice' => 'pages#advice'
        get 'pages/contacted_exporter' => 'pages#contacted_exporter'
        get 'pages/broker_option' => 'pages#broker_option'
        get 'pages/welcome' => 'pages#welcome'
        get 'pages/broker_default' => 'pages#broker_default'
        get 'pages/products' => 'pages#products'
        get 'pages/advice_insurance' => 'pages#advice_insurance'
        get 'pages/advice_credit' => 'pages#advice_credit'
        get 'pages/advice_refinance' => 'pages#advice_refinance'
        get 'pages/invite_or_fill_yourself_export_appilcation' => 'pages#invite_or_fill_yourself_export_appilcation'
        get 'pages/invite_or_fill_yourself_insurance' => 'pages#invite_or_fill_yourself_insurance'
        get 'pages/application_submitted' => 'pages#application_submitted'
        get 'pages/importer_information_saved' => 'pages#importer_information_saved'
        get 'pages/document_prefill_saved' => 'pages#document_prefill_saved'
        get 'pages/webid_instructions' => 'pages#webid_instructions'
        get 'pages/candis' => 'pages#candis'

        resources :insurances
        resources :export_applications
        resources :credits
        resources :invite_exporters
        resources :refinances
        resources :onboardings
        resources :importer_informations

        resources :users, only: [:show] do
            member do
                get 'submitted_applications'
                get 'approved_applications'
                get 'draft_applications'
                get 'all_applications'
                get 'invite_exporters'
                get 'broker_filled_applications'
            end
        end
    end
	
end

app/models/export_application.rb
class ExportApplication < ApplicationRecord
    belongs_to :user

    has_many :invite_importers, dependent: :destroy
    has_many :supplies_from_foreign_origins, dependent: :destroy
    has_many :guarantees, dependent: :destroy
    has_many :agreed_payments, dependent: :destroy
    has_many :agreed_payment_mid_longs, dependent: :destroy
    has_many :multiple_shipments, dependent: :destroy
    has_many :source_of_funds, dependent: :destroy
    has_many :application_of_funds, dependent: :destroy
    has_many :extra_billed_items, dependent: :destroy
    has_many :special_repayment_profiles, dependent: :destroy
    has_many :peps, dependent: :destroy
    
    accepts_nested_attributes_for :invite_importers,
                                  allow_destroy: true

    accepts_nested_attributes_for :supplies_from_foreign_origins,
                                  allow_destroy: true

    accepts_nested_attributes_for :guarantees,
                                  allow_destroy: true

    accepts_nested_attributes_for :agreed_payments,
                                  allow_destroy: true

    accepts_nested_attributes_for :agreed_payment_mid_longs,
                                  allow_destroy: true

    accepts_nested_attributes_for :multiple_shipments,
                                  allow_destroy: true

    accepts_nested_attributes_for :source_of_funds,
                                  allow_destroy: true

    accepts_nested_attributes_for :application_of_funds,
                                  allow_destroy: true

    accepts_nested_attributes_for :extra_billed_items,
                                  allow_destroy: true

    accepts_nested_attributes_for :special_repayment_profiles,
                                  allow_destroy: true

    accepts_nested_attributes_for :peps,
                                  allow_destroy: true
    
    has_attached_file :annual_financial_statement_importer, :storage => :cloudinary, :cloudinary_resource_type => :image, :path => "export_applications/:attachment/:id/:style/:filename",
                      styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :annual_financial_statement_importer, content_type: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf']
    
    has_attached_file :annual_financial_statement_importer_second_last, :storage => :cloudinary, :cloudinary_resource_type => :image,  :path => "export_applications/:attachment/:id/:style/:filename",
                      styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :annual_financial_statement_importer_second_last, content_type: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf']

    has_attached_file :annual_financial_statement_exporter, :storage => :cloudinary, :cloudinary_resource_type => :image, :path => "export_applications/:attachment/:id/:style/:filename",
                      styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :annual_financial_statement_exporter, content_type: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf']

    has_attached_file :annual_financial_statement_exporter_second_last, :storage => :cloudinary, :cloudinary_resource_type => :image, :path => "export_applications/:attachment/:id/:style/:filename",
                      styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :annual_financial_statement_exporter_second_last, content_type: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf']

    has_attached_file :export_contract_or_bills, :storage => :cloudinary,  :cloudinary_resource_type => :image, :path => "export_applications/:attachment/:id/:style/:filename",
                      styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :export_contract_or_bills, content_type: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf']
    
    has_attached_file :credit_bureaus_importer, :storage => :cloudinary, :cloudinary_resource_type => :image,  :path => "export_applications/:attachment/:id/:style/:filename",
                      styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :credit_bureaus_importer, content_type: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf']

    has_attached_file :self_declaration, :storage => :cloudinary, :cloudinary_resource_type => :image,  :path => "export_applications/:attachment/:id/:style/:filename",
                      styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :self_declaration, content_type: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf']

    has_attached_file :project_memorandum_exporter_business, :storage => :cloudinary, :cloudinary_resource_type => :image,  :path => "export_applications/:attachment/:id/:style/:filename",
                      styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :project_memorandum_exporter_business, content_type: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf']

    has_attached_file :environment_social_audit, :storage => :cloudinary, :cloudinary_resource_type => :image,  :path => "export_applications/:attachment/:id/:style/:filename",
                      styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :environment_social_audit, content_type: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf']
	
end

app/helpers/export_applications_helper.rb
module ExportApplicationsHelper
end

app/views/export_applications/_draft_listing.html.erb
<div class="row">
  <% applications.each do |export_application| %>
    <%= render partial: "export_applications/draft_application_listing_card",
               locals:  {export_application: export_application,
                        can_edit: can_edit} %>
  <% end %>
</div>

app/views/export_applications/_overview_content.html.erb
<div class="overview_content">
    <div class="row">
        <div class="col s12">
            <ul class="tabs">
                <li class="tab col s3"><a class="active" href="#company"><%= t('company') %></a></li>
                <li class="tab col s3"><a href="#your_importer"><%= t('your_importer') %></a></li>
                <li class="tab col s3"><a href="#business_heading"><%= t('business_heading') %></a></li>
                <li class="tab col s3"><a href="#finance_and_payment"><%= t('finance_and_payment') %></a></li>
            </ul>
        </div>
        <div id="company" class="col s12">
            <div class="handex-form-container">
                <div class="container">
                    <div class="section">
                        
                        <ul class="collection with-header">
                            <% @export_application.attributes.each do |attr_name, attr_value|
                                next if (attr_name == "id" or !@company_attr_list.include? attr_name)    %>
                                <li class="collection-item">
                                    <div class="overview-item">
                                        <%= t(attr_name) %>
                                    </div>
                                    <div class="secondary-content">
                                        <%= if !attr_value.nil? and attr_value == t('please_select')
                                                t('not_selected_yet')
                                            elsif !attr_value.nil? and attr_value == "export_application"
                                                t('export_application')
                                            elsif !attr_value.nil? and !attr_value
                                                t('no')
                                            elsif !attr_value.nil? and attr_value == true
                                                t('yes')
                                            elsif !attr_name.nil? and attr_name != '' and (attr_value.nil? or attr_value == '')
                                                t('no_value')
                                            elsif !attr_value.nil?
                                                attr_value
                                            end %>
                                    </div>
                                </li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div id="your_importer" class="col s12">
            <div class="handex-form-container">
                <div class="container">
                    <div class="section">
                        
                        <ul class="collection with-header">
                            <% @export_application.attributes.each do |attr_name, attr_value|
                                next if (attr_name == "id" or !@your_importer_attr_list.include? attr_name)     %>
                                <li class="collection-item">
                                    <div class="overview-item">
                                        <%= t(attr_name) %>
                                    </div>
                                    <div class="secondary-content">
                                        <%= if !attr_value.nil? and attr_value == t('please_select')
                                                t('not_selected_yet')
                                            elsif !attr_value.nil? and attr_value == "export_application"
                                                t('export_application')
                                            elsif !attr_value.nil? and !attr_value
                                                t('no')
                                            elsif !attr_value.nil? and attr_value == true
                                                t('yes')
                                            elsif !attr_name.nil? and attr_name != '' and (attr_value.nil? or attr_value == '')
                                                t('no_value')
                                            elsif !attr_value.nil?
                                                attr_value
                                            end %>
                                    </div>
                                </li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div id="business_heading" class="col s12">
            <div class="handex-form-container">
                <div class="container">
                    <div class="section">
                        
                        <ul class="collection with-header">
                            <% @export_application.attributes.each do |attr_name, attr_value|
                                next if (attr_name == "id" or !@business_attr_list.include? attr_name)      %>
                                <li class="collection-item">
                                    <div class="overview-item">
                                        <%= t(attr_name) %>
                                    </div>
                                    <div class="secondary-content">
                                        <%= if !attr_value.nil? and attr_value == t('please_select')
                                                t('not_selected_yet')
                                            elsif !attr_value.nil? and attr_value == "export_application"
                                                t('export_application')
                                            elsif !attr_value.nil? and !attr_value
                                                t('no')
                                            elsif !attr_value.nil? and attr_value == true
                                                t('yes')
                                            elsif !attr_name.nil? and attr_name != '' and (attr_value.nil? or attr_value == '')
                                                t('no_value')
                                            elsif !attr_value.nil?
                                                attr_value
                                            end %>
                                    </div>
                                </li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div id="finance_and_payment" class="col s12">
            <div class="handex-form-container">
                <div class="container">
                    <div class="section">
                        
                        <ul class="collection with-header">
                            <% @export_application.attributes.each do |attr_name, attr_value|
                                next if (attr_name == "id" or !@finance_and_payment_attr_list.include? attr_name)      %>
                                <li class="collection-item">
                                    <div class="overview-item">
                                        <%= t(attr_name) %>
                                    </div>
                                    <div class="secondary-content">
                                        <%= if !attr_value.nil? and attr_value == t('please_select')
                                                t('not_selected_yet')
                                            elsif !attr_value.nil? and attr_value == "export_application"
                                                t('export_application')
                                            elsif !attr_value.nil? and !attr_value
                                                t('no')
                                            elsif !attr_value.nil? and attr_value == true
                                                t('yes')
                                            elsif !attr_name.nil? and attr_name != '' and (attr_value.nil? or attr_value == '')
                                                t('no_value')
                                            elsif !attr_value.nil?
                                                attr_value
                                            end %>
                                    </div>
                                </li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.tabs').tabs();
    });
</script>

app/views/export_applications/_overview_header.html.erb
<div class="overview-header">
    <div class="container center">
        <div class="col s12 m12">
            <ul>
                <li><%= t('importer') %>
                    <div class="overview_header_value">
                        <%= (@export_application.importer_company_name.nil? or (!@export_application.importer_company_name.nil? and @export_application.importer_company_name.to_s.empty?) or (!@export_application.importer_company_name.nil? and @export_application.importer_company_name.to_s == t('please_select'))) ? render('shared/missing_icon') : @export_application.importer_company_name %>
                    </div>
                </li>
                <li><%= t('product') %>
                    <div class="overview_header_value">
                        <%= (@export_application.exported_goods_type_two.nil? or (!@export_application.exported_goods_type_two.nil? and @export_application.exported_goods_type_two.to_s.empty?) or (!@export_application.exported_goods_type_two.nil? and @export_application.exported_goods_type_two.to_s == t('please_select')) or (!@export_application.exported_goods_type_two.nil? and @export_application.exported_goods_type_two.to_s == t('please_select_corresponding_option'))) ? render('shared/missing_icon') : @export_application.exported_goods_type_two %>
                    </div>
                </li>
                <li><%= t('contract_value') %>
                    <div class="overview_header_value">
                        <%= (@export_application.contract_value.nil? or (!@export_application.contract_value.nil? and @export_application.contract_value.to_s.empty?) or (!@export_application.contract_value.nil? and @export_application.contract_value.to_s == t('please_select'))) ? render('shared/missing_icon') : @export_application.contract_value %>
                    </div>
                </li>
                <li><%= t('application_sent_at') %>
                    <div class="overview_header_value">
                        <%= (@export_application.created_at.nil? or (!@export_application.created_at.nil? and @export_application.created_at.to_s.empty?) or (!@export_application.created_at.nil? and @export_application.created_at.to_s == t('please_select'))) ? render('shared/missing_icon') : @export_application.created_at %>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>

app/views/export_applications/_overview_top.html.erb
<div class="overview-top submitted">
  <div class="row">
    <div class="col s5 overview-top-icon">
      <%= link_to :back do %>
        <i class="material-icons">arrow_back</i>
      <% end %>
    </div>
    <div class="col s6 overview-top-icon">
      <div class="valign-wrapper">
        <i class="material-icons">timer</i>
        <div>
          <strong><%= t('application_sent') %></strong>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/export_applications/_overview_top_approved.html.erb
<div class="overview-top approved">
    <div class="row">
        <div class="col s5 overview-top-icon">
            <%= link_to :back do %>
                <i class="material-icons">arrow_back</i>
            <% end %>
        </div>
        <div class="col s6 overview-top-icon">
            <div class="valign-wrapper">
                <i class="material-icons">timer</i>
                <div>
                    <strong> Antrag genehmigt </strong>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/export_applications/_overview_top_editable.html.erb
<div class="overview-top draft">
    <div class="row">
        <div class="col s4 overview-top-icon">
            <%= link_to :back do %>
                <i class="material-icons">arrow_back</i>
            <% end %>
        </div>
        <div class="col s4 overview-top-icon">
            <div class="valign-wrapper">
                <div class="valign h_centered">
                    <i class="custom_icon reciept-icon-white"></i>
                    <strong><%= t('draft_application') %></strong>
                </div>
            </div>
        </div>
        <div class="col s4 overview-top-button">
            <%= form_for(@export_application, local: true, html: {multipart: true}, id: "export-application-portal") do |form| %>
                <%= link_to t('edit'), edit_export_application_path(@export_application), class: "btn handex-btn z-depth-0 right" %>
            <% end %>
        </div>
    </div>
</div>

app/views/export_applications/_show_editable.html.erb
<%= render 'shared/navbar' %>
<p id="notice" class="" hidden><%= notice %></p>
<%= render "overview_top_editable.html.erb"%>
<%= render "overview_header.html.erb"%>
<%= render "overview_content.html.erb"%>

app/views/export_applications/_show_non_editable.html.erb
<%= render 'shared/navbar' %>
<p id="notice" class="" hidden><%= notice %></p>
<%= render "overview_top.html.erb"%>
<%= render "overview_header.html.erb"%>
<%= render "overview_content.html.erb"%>

app/views/export_applications/_show_non_editable_approved.html.erb
<%= render 'shared/navbar' %>
<p id="notice" class="" hidden><%= notice %></p>
<%= render "overview_top_approved.html.erb"%>
<%= render "overview_header.html.erb"%>
<%= render "overview_content.html.erb"%>

app/views/export_applications/edit.html.erb
<%= render 'shared/navbar' %>
<%= render 'form', export_application: @export_application %>

app/views/export_applications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Export Applications</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @export_applications.each do |export_application| %>
      <tr>
        <td><%= link_to 'Show', export_application %></td>
        <td><%= link_to 'Edit', edit_export_application_path(export_application) %></td>
        <td><%= link_to 'Destroy', export_application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Export Application', new_export_application_path %>

app/views/export_applications/new.html.erb
<%= render 'shared/navbar' %>
<%= render 'form', export_application: @export_application %>

app/views/export_applications/show.html.erb
<% if @export_application.application_status == "SUBMITTED" %>
    <%= render "show_non_editable.html.erb" %>
<% elsif @export_application.application_status == "APPROVED" %>
    <%= render "show_non_editable_approved.html.erb" %>
<% elsif @export_application.application_status == "DRAFT" %>
    <%= render "show_editable.html.erb" %>
<% end %>